# 프로그래밍 언어 비유 {#programming-language-tropes}

## hello, world {#helloworld}

hello, world 혹은 헬로월드

```
#include <stdio.h>

main( )
{
        printf("hello, world\n");
}
```

브라이언 케니건이 The C Programming Language (K&R) 서적 (1974) 에서 작성한 hello, world 프로그램.

위와 같이 정석은 `hello, world` 지만 뭐 애초에 stdout 을 사용해본다는데 의미가 있기 때문에 `helloworld`, `Hello World!` ~~, `나 아이돌 그만둘래!`, `asdfsdfdsf`~~ 등의 여러가지 구현 방식을 볼 수 있다.

프로그래밍 언어를 연습하기 위해 최초로 작성해보는 프로그램. 프로그래밍 언어 자체보다도 개발환경을 제대로 인스톨했는지, IDE를 제대로 다룰 수 있는지, 혹은 컴파일 및 결과물 실행 방식을 제대로 이해하고 있는지가 더 관건인 테스트 프로그램에 더 가깝다.

당시의 개발환경으로는 초보자에게 쉽지않은 과제였다. 저 최초의 헬로월드를 구현하기 위해선 우선 1) 운영체제를 설치할 수 있어야 했고, 2) C 를 설치할 수 있어야 했으며, 3) 그리고 libc 와 연동시켜서 컴파일하는 등의 환경 설정을 해야했다. 뭐 빌드가 쉬운 일이 아니었던 예전의 이야기이다. 요즘의 언어들은 아예 애초에 기본으로 운영체제 내부에 기본 설치되어 있는 경우가 많고, 그렇지 않더라도 패키지매니저 등으로 매우 간단히 설치할 수 있다. 프로그램 자체도 그냥 대화창 열어서 한줄치면 interactive 하게 결과 나온다.

Esoteric language 에 한정해서 그 기괴함을 알리기 위한 광고효과로 쓰기도 한다.

프로그래밍 언어 뿐 아니라 아주 기초적인 동작을 확인하는 테스트 프로그램들도 stdout 으로 결과출력하는 식으로 동작하기에 역시 헬로월드 프로그램으로 불리기도 한다. 가령 ESA 의 로제타가 구동 완료 메세지를 [헬로월드](https://twitter.com/esa_rosetta/status/425331522363596801)라고 트위터에 전송하는 것으로 시행하였다.

개발 환경과 생산성이 좋아진 요즘에는 단순한 stdout 출력은 잘 쓰이지 않는다. 가령 3분만에 게시물 만들기 같은 식으로 과거와 달리 엄청난 생산성을 보여주는 프로그램들이 이를 대체하고 있다. 하지만 눈에 보이는 결과물을 통해 소프트웨어에 익숙해지게 한다는 본질은 변하지 않는다.

### 같이 보기

* [헬로월드 언어별 모음](http://helloworldcollection.de/)
* [나 아이돌 그만둘래!](https://github.com/xnuk/idoru-yameru)

## 0번째 {#zeroth}
일상어로 첫번째를 의미. C나 리스프 같은 초기 언어는 물론 하드웨어부터 1이 아니라 0부터 세는데 익숙해지다보니 저렇게 표현하곤 한다. 가령 0-255 는 일상어로 1-256을 의미한다.

## camelCase {#camelCase}
camelCaseIsThePracticeOfWritingCompoundWordsOrPhrasesSuchThatEachWordOrAbbreviationInTheMiddleOfThePhraseBeginsWithACapitalLetterWithNoSpacesOrHyphens - [wikipedia](https://en.wikipedia.org/wiki/Camel_case)

자바에서의 표기법으로 유명하지만, 본래 파스칼에서 사용하던 표기법이다. 그래서 본래 PascalCase 라고 불렸다. 파스칼이 망하면서 같이 망할 줄 알았지만 자바에서 살아남았다. 그리고 자바 계열 언어에서 주로 쓰인다.

위의 예제와 같이 조금만 길어지면 보기 힘들다.

[snake_case](#snake_case)와는 상극으로 여겨지는 경향이 있지만 꼭 그렇지도 않다. R 처럼  둘을 섞어쓰는 언어도 있고, 아예 그 둘의 혼종인 `Train-Case` 표기법도 있다.

## snake_case {#snake_case}
snake_case_is_the_practice_of_writing_compound_words_or_phrases_in_which_the_elements_are_separated_with_one_underscore_character_and_no_spaces - [wikipedia](https://en.wikipedia.org/wiki/Snake_case)

C 계열 언어에서 주로 사용. 예외라면 ObjC 가 있다.

## kebab-case {#kebab-case}
[snake_case](#snake_case)와 유사하나`underscores` 대신에 `hyphens`을 사용하는 경우 `kebab-case` 라고 한다. 주로 Lisp 에서 사용한다.

## 갓언어 {#god-language}
~~파이썬은 망해가는 언어이고 PHP는 부활해서 1위를 탈환할 언어다~~

완벽한 언어. 해당 언어외 다른 언어를 고려할 여지가 없다는 식의 압도적인 강점을 보유하고 있는 언어를 말한다.

실제로는 엉망인 언어를 비꼬는 경우가 많다. [참조](https://www.google.se/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiD4PSJtcHQAhXMB8AKHSKmCgkQFggcMAA&url=https%3A%2F%2Ftwitter.com%2Fi%2Fmoments%2F788997459406000129&usg=AFQjCNGGG5if_BDRhoGbbmlCGb1-9NcXSQ)

## php {#php}

* http://noraesae.github.io/PHP-a-fractal-of-bad-design-kr/
* https://www.tokyobranch.net/archives/6693